### ISSUE TITLE
[Documentation Update]: Need to create Requirement.txt file for the Project Setup.

### ISSUE THREAD

**Issue by swarupn17** [dmotts/yt-to-cloud-uploader#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Currently there is no requirement.txt file in the codebase. So the contributors can't setup the project.

### Suggested Change

I will make the requirement.txt file.

### Rationale

Contributors can easily setup the project by using the file.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by dmotts** [comment]
Thanks, @swarupn17!

**Comment by dmotts** [comment]
Sorry @swarupn17. Your requirements.txt is not relevant to this project. You may try opening another PR, if you wish to attempt again.

**Comment by dmotts** [comment]
Feel free to ask for assistance if you need or have any questions, @swarupn17.

**Comment by dmotts** [comment]
@swarupn17 Would you mind telling me how you discovered this project?
You may cast your vote/answer here -> #14 

Thanks in advance for your feedback!

**Comment by Brijeshthummar02** [comment]
@dmotts would you mind if i give it a shot.

**Comment by dmotts** [comment]
Hey @Brijeshthummar02, I want to give @swarupn17 some time to try at it first. Then if he's wants to give it up, I'll assign it to you. However, @swarupn17 if you're experiencing any challenges, you can start a chat/[discussions](https://github.com/dmotts/yt-to-cloud-uploader/discussions) with @Brijeshthummar02 to work together to come up with a solution!

In the meantime, @Brijeshthummar02 you may explore the other [issues](https://github.com/dmotts/yt-to-cloud-uploader/issues) or other [open source projects](https://github.com/stars/dmotts/lists/open-source-projects) and see if anything there interests you.

**Comment by swarupn17** [comment]
Hey @dmotts Can you tell me ehat exactly was  the problem with the previous PR ?

**Comment by dmotts** [comment]
Honestly @swarupn17, I can't remember... This is a project I really wanted to complete but other projects keep popping up so I decided to open source my projects instead of letting them die. I hope that explanation helps in some way.

If you have any other questions or need assistance, please do not hesitate to ask. ✋

**Comment by dmotts** [comment]
My bad @swarupn17, I miss interpreted your last statement 🤔

**Comment by swarupn17** [comment]
In the Readme.md file it is written that to setup project locally you need to run the command "pip install -r requirement.txt". But the requirement.txt file is missing in the codebase so any new contributor can setup the project. I added the file but don't know exactly why its not relevant to the project according to you.

**Comment by dmotts** [comment]
I'll break it down for @swarupn17 and @Brijeshthummar02. The requirements.txt file you added were filled with a list of dependencies, none related to the dependencies in the project. (https://github.com/swarupn17/yt-to-cloud-uploader/commit/d888d9efdba1c0c76be21ca74ef9125ebf41fda4)

![IMG_20241012_112028](https://github.com/user-attachments/assets/c3cffd22-a2ff-44e7-894c-1f4f0447d838)

![IMG_20241012_112123](https://github.com/user-attachments/assets/0ff43ee4-3054-4c4a-8ee8-c338eb8c095c)

I hope this make things a bit more clearer.

**Comment by dmotts** [comment]
@swarupn17 There is a python command that you can use to create the requirements file if you have it setup on your local machine.

**Comment by swarupn17** [comment]
@dmotts Ok Thanks for the explaination. I simply run the command "pip freeze > requirements.txt" to get requirement.txt file. I think it should be mentioned in the documentation that you have to first make requirement.txt file and then run the other commands.
Thanks!

**Comment by dmotts** [comment]
Thank you, @swarupn17! I greatly appreciate your feedback and contributions.🙌

Feel free to make any more suggestions either here or in the [issues](https://github.com/dmotts/yt-to-cloud-uploader/issues) or [discussions](https://github.com/dmotts/yt-to-cloud-uploader/discussions) section.

**Comment by HomerusJa** [comment]
Maybe we could use the following GitHub Action to automatically update the requirements.txt:

```yaml
name: Update Requirements

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          plugins: poetry-plugin-export
          virtualenvs-in-project: true
          virtualenvs-path: .venv

      - name: Export requirements.txt
        run: poetry export --without-hashes -f requirements.txt -o requirements.txt

      - name: Check for changes
        run: |
          git diff --exit-code requirements.txt || echo "Changes detected"

      - name: Create Pull Request
        if: success() && steps.check-for-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update requirements.txt"
          body: "Automatically updated requirements.txt"
          base: main
          head: update-requirements-branch
```
